using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CrystalData.Models
{
    [Table("Invoice")]
    public class InvoiceModel
    {
        public Guid GUIDInvoice { get; set; } 
        public string TxnID { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoiceNumberSort { get; set; }
        public Guid? GUIDOrder { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public string Type { get; set; }
        public Boolean PostedToAR { get; set; }
        public DateTime? DatePosted { get; set; }
        public Boolean Printed { get; set; }
        public DateTime? DatePrinted { get; set; }
        public Boolean ReadyToPrint { get; set; }
        public string BranchID { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? EntryDate { get; set; }
        public string EnteredBy { get; set; }
        public string CreditApprovedBy { get; set; }
        public DateTime? CreditApprovalDate { get; set; }
        public string ShipVia { get; set; }
        public string FOB { get; set; }
        public DateTime? RequestedShipDate { get; set; }
        public DateTime? ShipmentPromisedDate { get; set; }
        public string BackorderCriteria { get; set; }
        public Boolean ManualHold { get; set; }
        public string HoldReleasedBy { get; set; }
        public DateTime? HoldReleasedDate { get; set; }
        public Int16? NumberShipments { get; set; }
        public DateTime? LastShipmentDate { get; set; }
        public Boolean Completed { get; set; }
        public DateTime? DateCompleted { get; set; }
        public Guid? GUIDCustomer { get; set; }
        public string BillToName { get; set; }
        public string BillToAddress1 { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToAddress3 { get; set; }
        public string BillToAddress4 { get; set; }
        public string BillToCity { get; set; }
        public string BillToState { get; set; }
        public string BillToZip { get; set; }
        public string BillToCountry { get; set; }
        public Guid? GUIDLocation { get; set; }
        public Boolean ShipToOverride { get; set; }
        public string ShipToAttn { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToAddress3 { get; set; }
        public string ShipToAddress4 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToZip { get; set; }
        public string ShipToCountry { get; set; }
        public string PO { get; set; }
        public Boolean? Taxable { get; set; }
        public string TaxID { get; set; }
        public Decimal? ForeignSubTotal { get; set; }
        public Decimal? SubTotal { get; set; }
        public Decimal? InvoiceDiscountPct { get; set; }
        public Decimal? ForeignDiscountAmount { get; set; }
        public Decimal? DiscountAmount { get; set; }
        public Decimal? TaxPct { get; set; }
        public Decimal? FrtTaxPct { get; set; }
        public Decimal? ForeignSalesTax { get; set; }
        public Decimal? SalesTax { get; set; }
        public Decimal? ForeignShippingCharge { get; set; }
        public Decimal? ShippingCharge { get; set; }
        public Decimal? ForeignTotalAmount { get; set; }
        public Decimal? TotalAmount { get; set; }
        public string Reference { get; set; }
        public string TermsCode { get; set; }
        public string TermsDescription { get; set; }
        public DateTime? DiscountDate { get; set; }
        public Decimal? ForeignDiscountAvailable { get; set; }
        public Decimal? DiscountAvailable { get; set; }
        public DateTime? DueDate { get; set; }
        public string ContractID { get; set; }
        public string DeliveredTo { get; set; }
        public string DeliveredBy { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public Decimal? DeliveryMiles { get; set; }
        public Int32? NumberOfPackages { get; set; }
        public Decimal? PackageWeight { get; set; }
        public string ShippingInstructions { get; set; }
        public string SpecialInstructions { get; set; }
        public string Comment { get; set; }
        public string InvoiceText { get; set; }
        public string Note { get; set; }
        public Decimal? ForeignAmtPaid { get; set; }
        public Decimal? AmtPaid { get; set; }
        public string BankId { get; set; }
        public string CCExpDate { get; set; }
        public string CheckNo { get; set; }
        public Int32? MethodOfPayment { get; set; }
        public Guid? GUIDPaymentMethod { get; set; }
        public string ShipToPhoneNumber { get; set; }
        public string TrackingNumber { get; set; }
        public string ContactEMailAddress { get; set; }
        public string ContactPhoneNumber { get; set; }
        public Int32? TransactionPeriod { get; set; }
        public Int32? TransactionYear { get; set; }
        public string Carrier { get; set; }
        public string CarrierService { get; set; }
        public string CarrierAndService { get; set; }
        public string JobNumber { get; set; }
        public string Reference2 { get; set; }
        public DateTime? ExportDate { get; set; }
        public Boolean Exported { get; set; }
        public Decimal? RetainageAmount { get; set; }
        public Boolean RetainageBilled { get; set; }
        public DateTime? ContractDate { get; set; }
        public string ScheduleOfValuesType { get; set; }
        public string InvoiceReportID { get; set; }
        public string InvoiceDetailReportID { get; set; }
        public string InvoiceStyle { get; set; }
        public Decimal? PreviousAmount { get; set; }
        public Decimal? PreviousRetainage { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? GUIDSalesperson { get; set; }
        public string OrderNumber { get; set; }
        public string JobID { get; set; }
        public string CustomerID { get; set; }
        public string LocationID { get; set; }
        public string SalespersonID { get; set; }
        public string SalespersonName { get; set; }
        public Guid? GUIDTaxCategory { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string ContactName { get; set; }
        public string ContactFAX { get; set; }
        public string InvoiceFormat { get; set; }
        public Guid? GUIDTaxCode { get; set; }
        public string TaxCode { get; set; }
        public string TaxCodeDescription { get; set; }
        public string MarketingCode { get; set; }
        public string DiscountType { get; set; }
        public Guid? GUIDClass { get; set; }
        public Boolean DoNotSync { get; set; }
        public Boolean FromQB { get; set; }
        public Guid? GUIDTerms { get; set; }
        public Guid? GUIDARAccount { get; set; }
        public Guid? GUIDInvoiceDiscountAccount { get; set; }
        public Guid? GUIDShippingChargeAccount { get; set; }
        public Guid? GUIDRetainageGLAccount { get; set; }
        public string CCTransID { get; set; }
        public string CCAuthorizationCode { get; set; }
        public string CCMerchAcctNumber { get; set; }
        public string CCReconBatchID { get; set; }
        public Int32? CCPaymentGroupingCode { get; set; }
        public DateTime? CCTxnAuthTime { get; set; }
        public Int32? CCTxnAuthStamp { get; set; }
        public string CCNumber { get; set; }
        public Int32? CCAVSStreet { get; set; }
        public Int32? CCAVSZip { get; set; }
        public Int32? CCStatusCode { get; set; }
        public string CCStatusMessage { get; set; }
        public string Routing { get; set; }
        public Guid? GUIDRoute { get; set; }
        public Decimal? StopNumber { get; set; }
        public Boolean InDispute { get; set; }
        public Guid? GUIDBranch { get; set; }
        public Boolean TaxIncluded { get; set; }
        public string CustomerTaxID { get; set; }
        public string CompanyTaxID { get; set; }
        public Decimal ExchangeRate { get; set; } 
        public Decimal? ForeignBalance { get; set; }
        public Decimal? Balance { get; set; }
        public Decimal? ForeignPaymentDiscount { get; set; }
        public Decimal? PaymentDiscount { get; set; }
        public DateTime? LastPaymentDate { get; set; }
        public Int32? CollectionDays { get; set; }
        public string BillToAddress { get; set; }
        public string ShipToAddress { get; set; }
        public Decimal? ForeignTotalShippingCharges { get; set; }
        public Decimal? TotalShippingCharges { get; set; }
        public string ARAccountID { get; set; }
        public string InvoiceDiscountAccountID { get; set; }
        public string ShippingChargeAccountID { get; set; }
        public string RetainageGLAccountID { get; set; }
        public string Route { get; set; }
        public string Class { get; set; }
        public string PaymentMethod { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
    }
}
