using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CrystalData.Models
{
    [Table("OrdersAvailableToShip")]
    public class OrdersAvailableToShipModel
    {
        public Guid GUIDOrder { get; set; } 
        public string OrderNumber { get; set; } 
        public string OrderNumberSort { get; set; }
        public string Type { get; set; }
        public Guid? GUIDCustomerType { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? EntryDate { get; set; }
        public string EnteredBy { get; set; }
        public string OrderStatus { get; set; }
        public DateTime? StatusDate { get; set; }
        public string StatusChangedBy { get; set; }
        public Boolean Completed { get; set; }
        public string InvoiceFormat { get; set; }
        public Boolean Printed { get; set; }
        public Boolean ReadyToPrint { get; set; }
        public Boolean PickTicketPrinted { get; set; }
        public Boolean PickTicketReadyToPrint { get; set; }
        public Boolean ShippingDocumentPrinted { get; set; }
        public Boolean ShippingDocumentReadyToPrint { get; set; }
        public string CreditApprovedBy { get; set; }
        public DateTime? CreditApprovalDate { get; set; }
        public string ShipVia { get; set; }
        public string FOB { get; set; }
        public DateTime? RequestedShipDate { get; set; }
        public DateTime? ShipmentPromisedDate { get; set; }
        public DateTime? DontShipBefore { get; set; }
        public DateTime? DontShipAfter { get; set; }
        public Int32? QuotedDaysToShip { get; set; }
        public string BackorderCriteria { get; set; }
        public Boolean ManualHold { get; set; }
        public string HoldReleasedBy { get; set; }
        public DateTime? HoldReleasedDate { get; set; }
        public DateTime? LastShipmentDate { get; set; }
        public Guid? GUIDCustomer { get; set; }
        public Boolean SoldToOverride { get; set; }
        public string SoldToName { get; set; }
        public string SoldToAddress1 { get; set; }
        public string SoldToAddress2 { get; set; }
        public string SoldToAddress3 { get; set; }
        public string SoldToAddress4 { get; set; }
        public string SoldToCity { get; set; }
        public string SoldToState { get; set; }
        public string SoldToZip { get; set; }
        public string SoldToCountry { get; set; }
        public Guid? GUIDLocation { get; set; }
        public Boolean ShipToOverride { get; set; }
        public string ShipToAttn { get; set; }
        public string ShipToDescription { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToAddress3 { get; set; }
        public string ShipToAddress4 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToZip { get; set; }
        public string ShipToCountry { get; set; }
        public DateTime? ShipWorkstationExportDate { get; set; }
        public string PO { get; set; }
        public Boolean? Taxable { get; set; }
        public Guid? GUIDTaxCode { get; set; }
        public Decimal? TaxPct { get; set; }
        public Decimal? FrtTaxPct { get; set; }
        public string TaxPercentText { get; set; }
        public Decimal? ForeignSchedSubTotal { get; set; }
        public Decimal? SchedSubTotal { get; set; }
        public Decimal? ForeignSchedDiscountAmount { get; set; }
        public Decimal? SchedDiscountAmount { get; set; }
        public Decimal? ForeignSchedSalesTax { get; set; }
        public Decimal? SchedSalesTax { get; set; }
        public Decimal? ForeignSchedShippingCharge { get; set; }
        public Decimal? SchedShippingCharge { get; set; }
        public Decimal? ForeignSchedTotalAmount { get; set; }
        public Decimal? SchedTotalAmount { get; set; }
        public Decimal? ForeignSubTotal { get; set; }
        public Decimal? SubTotal { get; set; }
        public string DiscountType { get; set; }
        public Decimal? InvoiceDiscountPct { get; set; }
        public Decimal? ForeignDiscountAmount { get; set; }
        public Decimal? DiscountAmount { get; set; }
        public Decimal? ForeignSalesTax { get; set; }
        public Decimal? SalesTax { get; set; }
        public Decimal? ForeignTotalAmount { get; set; }
        public Decimal? TotalAmount { get; set; }
        public string Reference { get; set; }
        public string TermsDescription { get; set; }
        public Decimal? ForeignSchedTermsDiscountAvailable { get; set; }
        public Decimal? SchedTermsDiscountAvailable { get; set; }
        public string NextInvoiceNumber { get; set; }
        public string ContractID { get; set; }
        public string JobNumber { get; set; }
        public string DeliveredTo { get; set; }
        public string DeliveredBy { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public Decimal? DeliveryMiles { get; set; }
        public Int32? NumberOfPackages { get; set; }
        public Decimal? PackageWeight { get; set; }
        public string ShippingInstructions { get; set; }
        public string SpecialInstructions { get; set; }
        public string Comment { get; set; }
        public string LostBusinessCode { get; set; }
        public string LostBusinessComment { get; set; }
        public string Note { get; set; }
        public string TrackingNumber { get; set; }
        public string Reference2 { get; set; }
        public string ContactName { get; set; }
        public string ContactPhoneNumber { get; set; }
        public string ContactFax { get; set; }
        public string ContactEMailAddress { get; set; }
        public Decimal? ForeignPendingShippingCharges { get; set; }
        public Decimal? PendingShippingCharges { get; set; }
        public Decimal? ForeignAmtPaid { get; set; }
        public Decimal? AmtPaid { get; set; }
        public string BankId { get; set; }
        public string CCExpDate { get; set; }
        public string CheckNo { get; set; }
        public Decimal? DiscAmt { get; set; }
        public Int32? MethodOfPayment { get; set; }
        public Guid? GUIDPaymentMethod { get; set; }
        public string PaymentMethod { get; set; }
        public Boolean ReadyToInvoice { get; set; }
        public Boolean InvoicingError { get; set; }
        public string InvoicingErrorMessage { get; set; }
        public string Carrier { get; set; }
        public string CarrierService { get; set; }
        public string CarrierAndService { get; set; }
        public Int16? NextShipmentNumber { get; set; }
        public string MarketingCode { get; set; }
        public Guid? GUIDSalesperson { get; set; }
        public Guid? GUIDTaxCategory { get; set; }
        public Guid? GUIDClass { get; set; }
        public Guid? GUIDOrderWorkFlowStatus { get; set; }
        public string WorkFlowStatusChangedBy { get; set; }
        public DateTime? WorkFlowStatusDate { get; set; }
        public Guid? GUIDTerms { get; set; }
        public string CCNumber { get; set; }
        public string CCName { get; set; }
        public string CCAddress { get; set; }
        public string CCPostalCode { get; set; }
        public string BeingPickedBy { get; set; }
        public Guid? GUIDRoute { get; set; }
        public Decimal? StopNumber { get; set; }
        public Guid? GUIDBranch { get; set; }
        public Boolean TaxIncluded { get; set; }
        public Guid? GUIDTemplate { get; set; }
        public string WebOrderNumber { get; set; }
        public string WebOrderID { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string OriginType { get; set; } 
        public string OriginID { get; set; }
        public Decimal ExchangeRate { get; set; } 
        public Guid? GUIDRelatedOrder { get; set; }
        public string RelatedOrderNumber { get; set; }
        public string BranchID { get; set; }
        public string SalespersonID { get; set; }
        public string SalespersonName { get; set; }
        public string CustomerID { get; set; }
        public string CompanyName { get; set; }
        public string LocationID { get; set; }
        public string TaxCatID { get; set; }
        public string SoldToAddress { get; set; }
        public string ShipToAddress { get; set; }
        public Decimal? ForeignTotalShippingCharges { get; set; }
        public Decimal? TotalShippingCharges { get; set; }
        public string TermsCode { get; set; }
        public string WorkFlowStatus { get; set; }
        public string WorkFlowStatusAbbreviation { get; set; }
        public string Route { get; set; }
        public string Class { get; set; }
        public string OrderStatusDescription { get; set; } 
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string CustomerTaxID { get; set; }
        public string CompanyTaxID { get; set; }
        public string TemplateID { get; set; }
        public Boolean? FromEDI { get; set; }
        public Boolean? WebOrder { get; set; }
        public Decimal? _PreShipmentDeposit { get; set; }
        public string _SalesLeadTime { get; set; }
        public string _ShippingTerms { get; set; }
        public DateTime? TodaysDate { get; set; }
        public Int32? Packages { get; set; }
        public string Routing { get; set; }
        public string UPSShipNotification { get; set; }
        public string UPSNotifcationRecipientType { get; set; } 
        public string UPSOptionYes { get; set; }
        public string UPSOptionNo { get; set; }
        public string UPSCODOption { get; set; }
    }
}
