using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CrystalData.Models
{
    [Table("Product")]
    public class ProductModel
    {
        public string ProductID { get; set; } 
        public Boolean TaxByCategory { get; set; }
        public Boolean TaxInPrice { get; set; }
        public Boolean AllowOverride { get; set; }
        public Boolean AllowZero { get; set; }
        public Int16? CommissionType { get; set; }
        public Decimal? CommPct { get; set; }
        public Decimal? CommAmt { get; set; }
        public string Unit { get; set; }
        public Decimal? Weight { get; set; }
        public Decimal? Length { get; set; }
        public Boolean VariableWeight { get; set; }
        public Boolean VariableLength { get; set; }
        public string Specification { get; set; }
        public string ProductPriceCategory { get; set; }
        public Boolean PriceByCategory { get; set; }
        public Int32? LeadTime { get; set; }
        public string SalesCategory { get; set; }
        public Boolean Discontinued { get; set; }
        public string CostMethod { get; set; }
        public string ProductType { get; set; }
        public string InventoryControlType { get; set; }
        public string AssemblyType { get; set; }
        public string CountCycle { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Boolean Status { get; set; }
        public string Note { get; set; }
        public Boolean Popup { get; set; }
        public string Color { get; set; }
        public Decimal? Height { get; set; }
        public string Size { get; set; }
        public Boolean VariableHeight { get; set; }
        public Boolean VariableVolume { get; set; }
        public Boolean VariableWidth { get; set; }
        public Decimal? Volume { get; set; }
        public Decimal? Width { get; set; }
        public string TechSpec { get; set; }
        public string WebAddress { get; set; }
        public string Description { get; set; }
        public Guid GUIDProduct { get; set; } 
        public Boolean NotForResale { get; set; }
        public Int32 MaintainInventoryType { get; set; } 
        public Boolean AvailOnWeb { get; set; }
        public Guid? GUIDTaxCategory { get; set; }
        public Byte[]? ProductPicture { get; set; }
        public Boolean ShipCompleteLots { get; set; }
        public string PONote { get; set; }
        public Boolean POPopup { get; set; }
        public Decimal? AltWeight { get; set; }
        public Decimal? AltLength { get; set; }
        public Decimal? AltHeight { get; set; }
        public Decimal? AltWidth { get; set; }
        public Decimal? AltVolume { get; set; }
        public Decimal? AltUnitsPerPalletLayer { get; set; }
        public Decimal? PalletLayers { get; set; }
        public Boolean Discountable { get; set; }
        public Guid? GUIDProductClass { get; set; }
        public Decimal? InnerPackQty { get; set; }
        public Decimal? OuterPackQty { get; set; }
        public string SalesUnit { get; set; }
        public Decimal? SalesUnitFactor { get; set; }
        public string SalesFactorBasis { get; set; }
        public string SalesBasis { get; set; }
        public string PurchaseUnit { get; set; }
        public Decimal? PurchaseUnitFactor { get; set; }
        public string PurchaseFactorBasis { get; set; }
        public string PurchaseBasis { get; set; }
        public string PackageUnit { get; set; }
        public Decimal? PackageUnitFactor { get; set; }
        public string PackageFactorBasis { get; set; }
        public string PackageBasis { get; set; }
        public Guid? SalesGUIDTaxCode { get; set; }
        public Guid? PurchaseGUIDTaxCode { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Decimal? LandedCostFactor { get; set; }
        public string AltDescription { get; set; }
        public string AlternateProductID { get; set; }
        public string UPC { get; set; }
        public string ShortDescription { get; set; }
        public Decimal? PiecesPerStockUnit { get; set; }
        public string ProductClassID { get; set; }
        public string ItemType { get; set; }
        public string Keywords { get; set; }
        public string ExternalDocument { get; set; }
        public string AlternateUnit { get; set; }
        public Decimal? AlternateUnitConversionFactor { get; set; }
        public Guid? PreferredGUIDVendor { get; set; }
        public string PreferredVendorID { get; set; }
        public Decimal? ListPrice { get; set; }
        public string ListPriceType { get; set; }
        public string ListPriceUnit { get; set; }
        public Boolean? ListPriceTaxIncluded { get; set; }
        public Boolean? Taxable { get; set; }
        public Boolean _Control { get; set; }
        public string _ControlDataType { get; set; }
        public string _ControlActivityType { get; set; }
        public string _ControlActivityStatus { get; set; }
        public string _ControlAssignTo { get; set; }
        public string _ControlMethod { get; set; }
        public string _ControlSpec { get; set; }
        public Decimal? _ControlMin { get; set; }
        public Decimal? _ControlMax { get; set; }
        public string _ControlOutput { get; set; }
        public string _ControlOrderWorkflowStatus { get; set; }
        public string _ControlProductionWorkflow { get; set; }
        public string _ControlGroup { get; set; }
        public Decimal? _HoursToComplete { get; set; }
        public Boolean _EssentialManufacturingSpecs { get; set; }
        public Decimal? _ServingsPerContainer { get; set; }
        public Decimal? _UnitsPerServing { get; set; }
        public Decimal? _WeightVarIndivToAvg { get; set; }
        public Decimal? _WeightVarAvgToLabel { get; set; }
        public Decimal? _MfgOverage { get; set; }
        public Boolean _InactiveIngredient { get; set; }
        public string _Analyte { get; set; }
        public Boolean _AdjustForPotency { get; set; }
        public Decimal? _Potency { get; set; }
        public Boolean _EssentialQcSpecs { get; set; }
        public string _LabelClaims { get; set; }
        public string _ShelfLife { get; set; }
        public string _StorageConditions { get; set; }
        public string _ServingDescription { get; set; }
        public string _Allergens { get; set; }
        public string _AllergenSeverity { get; set; }
        public string _GlutenRating { get; set; }
        public string _ConsumerWarnings { get; set; }
        public Boolean _OptionalManufacturingSpecs { get; set; }
        public string _LotLabelType { get; set; }
        public string _LotNumLocation { get; set; }
        public Boolean _CreateSubActivities { get; set; }
        public Boolean _NoSubassemblies { get; set; }
        public Decimal? _MaxBatchSize { get; set; }
        public string _BlendType { get; set; }
        public string _PackSize { get; set; }
        public Decimal? _OuterPacksPerPallet { get; set; }
        public string _PalletStackingInstructions { get; set; }
        public string _SubcontractMfg { get; set; }
        public Boolean _OptionalQCSpecs { get; set; }
        public string _ServingOccasion { get; set; }
        public Decimal? _ServingsPerDay { get; set; }
        public string _Scent { get; set; }
        public string _Taste { get; set; }
        public string _Appearance { get; set; }
        public string _Composition { get; set; }
        public string _Dissolution { get; set; }
        public string _CountryOrigin { get; set; }
        public Boolean _Analytic { get; set; }
        public Decimal? _ProjectionQty { get; set; }
        public string _CustomProductCategory { get; set; }
        public Boolean _Pricing { get; set; }
        public Decimal? _PerUnitLabor { get; set; }
        public Decimal? _PerUnitMachineOther { get; set; }
        public Decimal? _PerJobFreight { get; set; }
        public Decimal? _PerJobOther { get; set; }
        public Decimal? _ProfitMarginPercent { get; set; }
        public Decimal? _WastePercent { get; set; }
    }
}
